pkg/function/example/forward_msg/server/main.go, pkg/function/server/server.go, pkg/function/server/server_test.go
Signed-off-by: jyu6 <juanlu_yu@intuit.com>
fixes #6 
Testing
1.
```go
func main() {
file, _ := os.CreateTemp("/tmp", "numaflow-test.sock")
defer func() {
os.Remove(file.Name())
log.Println("clean up sock")
}()
var ctx, cancel = context.WithCancel(context.Background())
go func() {
time.Sleep(5 * time.Second)
log.Println("cancelling ctx...")
cancel()
}()
server.New().RegisterMapper(functionsdk.DoFunc(handle)).Start(ctx, server.WithSockAddr("/tmp/numaflow-test.sock"))
log.Println("Exit")
}
```
2. same main func but sent user interrupt
=> fix: add grpc server shutdown

pkg/function/server/server.go, pkg/sink/server/server.go
Return error instead of log.Fatal, fix #35
=> refactor: return error for server start

pkg/function/examples/event_time_filter/impl/filter_test.go, pkg/function/message.go, pkg/function/message_t.go, pkg/function/server/server_test.go, pkg/function/service.go
In MapT, it's important to assign new event times to ensure that default time values are not mistakenly passed to the next vertex. While our MapT SDKs offer methods like MessageTToAll() and MessageTTo() to create MessageT objects with explicit event times, users can also construct MessageT objects from scratch. However, if they forget to assign a new event time while modifying other attributes, default time values may be used unintentionally. 
To reduce this risk, we propose always requiring an explicit event assignment for MapT implementation. This code change achieves the proposal by un-exporting MessageT's attributes.
After this change, user can only use the following constructors to create MessageT objects:
```
functionsdk.MessageTToDrop()
```
```
functionsdk.MessageTTo(eventTime, …
```
=> refactor: un-export MessageT's attributes

go.mod, pkg/apis/proto/sink/v1/udsink.pb.go, pkg/apis/proto/sink/v1/udsink.proto, pkg/sink/clienttest/client_test.go, pkg/sink/examples/log/main.go, pkg/sink/interface.go, pkg/sink/server/server_test.go, pkg/sink/service.go, pkg/sink/service_test.go
This retracts release v.0.4.1. It also reverts the changes that expose metadata in udsink.
=> revert: metadata for udsink

pkg/function/client/client.go, pkg/function/client/options.go, pkg/function/server/server_test.go, pkg/info/server_info.go, pkg/info/server_info_test.go, pkg/info/types.go
In my recent [Java implementation](https://github.com/numaproj/numaflow-java/pull/36), I write the EOF on a newline, just to make it a bit clearer. I make the same changes here in Go SDK to make it consistent for parsing.
=> chore: fix some typos

pkg/function/client/client.go, pkg/function/clienttest/client_test.go, pkg/function/clienttest/clienttest.go, pkg/function/interface.go, pkg/function/server/server_test.go
This PR updates the newly added map stream interface from `MapStreamFn(ctx context.Context, datum *functionpb.DatumRequest, datumCh chan<- functionpb.DatumResponse) error` to `MapStreamFn(ctx context.Context, datum *functionpb.DatumRequest, datumCh chan<- *functionpb.DatumResponse) error`. 
Even though it is not recommended to use [pointers to channel](https://stackoverflow.com/questions/44351159/using-pointer-to-channel), without this change, when traverse from the client side response in numaflow, `go vet` will complain about:
> copylocks: range var datum copies lock: github.com/numaproj/numaflow-go/pkg/apis/proto/function/v1.DatumResponse contains google.golang.org/protobuf/internal/impl.MessageState contains sync.Mutex
See this …
=> chore: update map stream interface

pkg/sourcetransformer/messaget.go, pkg/sourcetransformer/service_test.go
Set the event time of messages to drop to epoch(0) - 1ms across all our SDKs.
=> chore: unify the event time of messages to drop

pkg/shared/util.go, pkg/sideinput/options.go, pkg/sideinput/server.go, pkg/sideinput/server_test.go
Implements: [Issue 1457](https://github.com/numaproj/numaflow/issues/1457) for the Go sdk
=> chore: write server info for sideinput sdk

pkg/sessionreducer/service_test.go, pkg/sessionreducer/task_manager.go
This change adds some unit tests covering cases when a merge operation is followed by non-close operations, verifying the blocking behavior of merge.
Also fixes a race condition issue when concurrently accessing the keyed window of a task.
=> chore: unit test merge operation as a blocking call

Makefile
This make target functionality is already implemented in the update script, can achieve the same result running:
`./hack/update_examples -bp -t test`
=> chore: remove duplicate functionality

pkg/info/server_info_test.go, pkg/info/types.go, pkg/mapper/examples/even_odd/go.mod, pkg/mapper/examples/flatmap/go.mod, pkg/mapper/examples/forward_message/go.mod, pkg/mapper/examples/retry/go.mod, pkg/mapper/examples/tickgen/go.mod, pkg/mapstreamer/examples/flatmap_stream/go.mod, pkg/reducer/examples/counter/go.mod, pkg/reducer/examples/sum/go.mod, pkg/reducestreamer/examples/counter/go.mod, pkg/reducestreamer/examples/sum/go.mod, pkg/sessionreducer/examples/counter/go.mod, pkg/sessionreducer/examples/sum/go.mod, pkg/sessionreducer/examples/sum/go.sum, pkg/shared/util.go, pkg/sideinput/examples/simple-sideinput/go.mod, pkg/sideinput/examples/simple-sideinput/udf/go.mod, pkg/sinker/examples/log/go.mod, pkg/sourcer/examples/simple_source/go.mod, pkg/sourcetransformer/examples/assign_event_time/go.mod, pkg/sourcetransformer/examples/event_time_filter/go.mod
related to: [#1504](https://github.com/numaproj/numaflow/issues/1504)
=> chore: add minimum client version to server info struct

pkg/info/server_info_test.go, pkg/info/types.go, pkg/shared/util.go
https://github.com/numaproj/numaflow-python/pull/152#discussion_r1557994247
=> chore: update server info field name

development.md, hack/update_examples.sh, releases.md
It is very unlikely that anyone will ever need to build and push all the example images locally while testing. In order to clean up the script remove this functionality, as it should only be done by Github Actions workflow.
=> chore: remove unnecessary flag

.github/workflows/build-push.yaml, pkg/mapper/examples/even_odd/Makefile, pkg/mapper/examples/flatmap/Makefile, pkg/mapper/examples/forward_message/Makefile, pkg/mapper/examples/retry/Makefile, pkg/mapper/examples/tickgen/Makefile, pkg/mapstreamer/examples/flatmap_stream/Makefile, pkg/reducer/examples/counter/Makefile, pkg/reducer/examples/sum/Makefile, pkg/reducestreamer/examples/counter/Makefile, pkg/reducestreamer/examples/sum/Makefile, pkg/sessionreducer/examples/counter/Makefile, pkg/sessionreducer/examples/sum/Makefile, pkg/sideinput/examples/map_sideinput/Makefile, pkg/sideinput/examples/map_sideinput/udf/Makefile, pkg/sideinput/examples/reduce_sideinput/Makefile, pkg/sideinput/examples/reduce_sideinput/udf/Makefile, pkg/sideinput/examples/sideinput_function/Makefile, pkg/sideinput/examples/simple_sideinput/Makefile, pkg/sideinput/examples/simple_sideinput/udf/Makefile, pkg/sideinput/examples/simple_source_with_sideinput/Makefile, pkg/sideinput/examples/sink_sideinput/Makefile, pkg/sinker/examples/fallback/Makefile, pkg/sinker/examples/log/Makefile, pkg/sinker/examples/redis-sink/Makefile, pkg/sourcer/examples/simple_source/Makefile, pkg/sourcetransformer/examples/assign_event_time/Makefile, pkg/sourcetransformer/examples/event_time_filter/Makefile
merge after #133 gets merged, so that we can add the same modifications to map batch example.
=> chore: stop hard coding quay.io image registry

pkg/batchmapper/examples/batchmap-flatmap/README.md, pkg/batchmapper/examples/batchmap-flatmap/pipeline.yaml, pkg/batchmapper/server.go, pkg/batchmapper/service.go, pkg/info/server_info.go, pkg/info/server_info_test.go, pkg/info/types.go, pkg/mapper/server.go, pkg/mapstreamer/server.go, pkg/mapstreamer/service.go, pkg/reducer/server.go, pkg/reducestreamer/server.go, pkg/sessionreducer/server.go, pkg/shared/util.go, pkg/sideinput/server.go, pkg/sinker/server.go, pkg/sourcer/server.go, pkg/sourcetransformer/server.go
Fixes https://github.com/numaproj/numaflow/issues/1838
=> feat: use same server info for all map modes

pkg/batchmapper/server.go, pkg/batchmapper/service.go, pkg/mapper/server.go, pkg/mapper/service.go, pkg/mapstreamer/server.go, pkg/mapstreamer/service.go, pkg/reducer/server.go, pkg/reducer/task_manager.go, pkg/reducestreamer/server.go, pkg/reducestreamer/task_manager.go, pkg/sessionreducer/server.go, pkg/sessionreducer/task_manager.go, pkg/shared/util.go, pkg/sideinput/server.go, pkg/sideinput/service.go, pkg/sinker/server.go, pkg/sinker/service.go, pkg/sourcer/server.go, pkg/sourcer/service.go, pkg/sourcetransformer/server.go, pkg/sourcetransformer/service.go
```
2024/08/29 09:24:07 panic inside reduce handler: reducer should not be invoked goroutine 26 [running]:
runtime/debug.Stack()
/usr/local/go/src/runtime/debug/stack.go:24 +0x64
github.com/numaproj/numaflow-go/pkg/reducer.(*reduceTaskManager).CreateTask.func1.1()
/Users/yhl01/Documents/numaproj/numaflow-go/pkg/reducer/task_manager.go:94 +0x40
panic({0x3f73c0?, 0x556758?})
/usr/local/go/src/runtime/panic.go:770 +0x124
main.reduceCounter({0x400017e040?, 0x9?}, {0x9?, 0x9?, 0x0?}, 0x0?, {0x40000465e8?, 0x32e2e8?})
/Users/yhl01/Documents/numaproj/numaflow-go/pkg/reducer/examples/counter/main.go:12 +0x2c
github.com/numaproj/numaflow-go/pkg/reducer.reducerFn.Reduce(0x4000046598?, {0x55bbf0?, 0x4000168d50?}, {0x40000970d0?, 0x0?, 0x4000169f80?}, 0x10?, {0x5583c0?, 0x4000097410?}) …
```
=> chore: log panics inside udf

pkg/info/server_info.go, pkg/info/server_info_test.go, pkg/info/types.go, pkg/mapper/server.go, pkg/mapstreamer/server.go, pkg/reducer/server.go, pkg/reducestreamer/server.go, pkg/sessionreducer/server.go, pkg/sideinput/server.go, pkg/sinker/server.go, pkg/sourcer/server.go, pkg/sourcetransformer/server.go
introduces one more dimension when checking version compatibly - container type.
=> feat: container-type level version compatibility check

.github/workflows/build-push.yaml, pkg/servingstore/examples/redis-store/go.mod, pkg/servingstore/examples/redis-store/go.sum
`quay.io/numaio/numaflow-go/serving-redis-store` and `quay.io/numaio/numaflow-go/sink-serve` images are referenced in Serving source examples in ` numaflow` repo.
=> chore: Publish sink-serve and redis-store images

pkg/accumulator/server.go, pkg/accumulator/service.go
```
2025/03/28 01:54:12 Starting server
2025/03/28 01:54:13 Watermark updated, flushing sortedBuffer:  1743126495631
2025/03/28 01:54:13 panic inside accumulator handler: invalid data goroutine 28 [running]:
runtime/debug.Stack()
/opt/homebrew/opt/go/libexec/src/runtime/debug/stack.go:26 +0x64
github.com/numaproj/numaflow-go/pkg/accumulator.(*accumulatorTaskManager).CreateTask.func1.2()
/Users/yhl01/Documents/numaproj/numaflow-go/pkg/accumulator/task_manager.go:138 +0x44
panic({0x451020?, 0x5c78e8?})
/opt/homebrew/opt/go/libexec/src/runtime/panic.go:792 +0x124
main.(*streamSorter).Accumulate(0x40001965a0, {0x5ce590, 0x400021a1e0}, 0x4000242620, 0x4000242690)
/Users/yhl01/Documents/numaproj/numaflow-go/pkg/accumulator/examples/streamsorter/main.go:38 +0x1ec …
```
=> fix: graceful shutdown in accumulator

pkg/accumulator/service.go, pkg/batchmapper/service.go, pkg/mapper/service.go, pkg/mapstreamer/service.go, pkg/reducer/service.go, pkg/reducestreamer/service.go, pkg/servingstore/service.go, pkg/sessionreducer/service.go, pkg/sinker/service.go, pkg/sourcetransformer/service.go
Client cancellation was triggering server shutdown and udf container restart.
If the error type is `context.Cancelled` we don't send shutdown signal to the server.
=> fix: client cancellation should not trigger grpc shutdown
